version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - 8080:8080
    container_name: jenkins
    volumes:
        - ./:/app

  web:
    image: node:16-alpine
    working_dir: /app
    volumes:
        - ./:/app
    env_file: ./.env
    ports:
        - 3000:3000
    command: ['npm', 'run', 'dev']